apiVersion: v1
kind: Pod
metadata: 
  name: "goserver"
  labels:
    app: "goserver"
spec:
  containers:
    - name: goserver
      image: gcr.io/still-entity-417217/lfcavalcante/hello-go@sha256:de27cebe29c190b3a95e4717b189566a66f28e6f3a131fc2919d357d46ac6696
  imagePullSecret:
  
